import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React, {Suspense} from "react";
import loading from "@/components/Loading";
import {ErrorBoundary} from "next/dist/client/components/error-boundary";
import NavbarComponent from "../components/NavbarComponent";
import Footer from "@/components/Footer";
import Error from "@/app/error";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Asto Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ErrorBoundary errorComponent={Error}>
          <NavbarComponent/>
          <Suspense fallback={loading()}>
              {children}
          </Suspense>
          <Footer/>
      </ErrorBoundary>
      </body>
    </html>
  );
}
