import type { Metadata } from "next";
import {Geist, Geist_Mono, Ubuntu_Mono} from "next/font/google";
import "./globals.css";
import {ErrorBoundary} from "next/dist/client/components/error-boundary";
import NavbarComponent from "../components/NavbarComponent";
import Footer from "@/components/Footer";
import Error from "@/app/error";
import {ThemeProvider} from "@/components/theme-provider";
import { Suspense } from "react";
import Loading from "@/components/Loading";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Astro Shop",
  description: "Generated by create next app",
};
const ubuntu = Ubuntu_Mono({
    variable: "--font-ubuntu-mono",
    subsets: ["latin"],
    weight: ["400", "700"],
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body
        className={`${ubuntu.variable} antialiased`}
      >
      <ErrorBoundary errorComponent={Error}>

          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem={true}
              disableTransitionOnChange={false}
          >
              <NavbarComponent/>
              <Suspense fallback={Loading()}>
              {children}
              </Suspense>
              <Footer/>
          </ThemeProvider>

      </ErrorBoundary>
      </body>
    </html>
  );
}
